"""Grounded Q&A for the floating GrantSetu AI assistant (POST /assistant/ask
-- api/routers/assistant.py).

The assistant must NEVER let an LLM invent a grant, deadline, funder,
amount, eligibility rule, application URL, or statistic. This module
enforces that by always resolving a `context` dict of REAL facts from the
database/analytics FIRST (see the `build_*_context` functions below), and
only ever handing the model that context as its sole source of truth, with
an explicit instruction not to add anything not present in it. If the
context doesn't contain an answer, the honest response is "GrantSetu does
not currently have that information" -- never a plausible-sounding guess.

Same AI-first/rule-based-fallback discipline as the rest of src/ai/: without
a configured provider (or on any AI failure), the assistant can't generate
conversational prose -- there's no model to do that -- but the same real
context is still returned, formatted as a direct, structured answer instead
of AI prose. This keeps "core functionality works without an AI key" honest
for a conversational feature instead of just disabling it outright.
"""
import json
from dataclasses import dataclass, field
from datetime import datetime

from src.ai.providers import AIProvider

MAX_CONTEXT_CHARS = 6000  # keeps the prompt small; contexts are already narrow (one opportunity/NGO/search's worth), never the full corpus


@dataclass
class AssistantAnswer:
    answer: str
    method: str  # "ai" | "rule_based"
    ai_disclaimer: str | None = None
    grounded_on: list[str] = field(default_factory=list)  # short labels of what real data was used
    data_available: bool = True


_SYSTEM_PROMPT = """You are GrantSetu's funding-intelligence assistant, helping an NGO understand funding opportunities and data GrantSetu has already retrieved. You must answer using ONLY the JSON facts given below -- never invent a grant, deadline, funder, amount, eligibility rule, application URL, or statistic that isn't in these facts. If the facts don't contain what's needed to answer, say plainly: "GrantSetu does not currently have that information" (then answer whatever part you legitimately can from what IS present). Never claim a probability of winning funding. Keep your answer to 2-5 short sentences, plain language, no markdown headers.

FACTS (JSON):
{facts}

QUESTION: {question}"""


def _rule_based_answer(facts: dict, grounded_on: list[str]) -> AssistantAnswer:
    """No AI configured (or AI failed) -- the assistant cannot generate a
    conversational answer to an arbitrary free-text question, so it honestly
    returns the real underlying facts directly, formatted for reading,
    rather than pretending to converse. The frontend labels this
    "Answered from GrantSetu data (AI not configured)" -- never presented as
    if it were a generated answer."""
    if not facts:
        return AssistantAnswer(
            answer="GrantSetu does not currently have that information.",
            method="rule_based",
            grounded_on=grounded_on,
            data_available=False,
        )
    lines = []
    for key, value in facts.items():
        if value in (None, "", [], {}):
            continue
        label = key.replace("_", " ").capitalize()
        if isinstance(value, list):
            value = ", ".join(str(v) for v in value[:6]) or "none listed"
        lines.append(f"{label}: {value}")
    body = "\n".join(lines) if lines else "No further details are available for this."
    return AssistantAnswer(
        answer=body,
        method="rule_based",
        grounded_on=grounded_on,
        data_available=bool(lines),
    )


def answer_question(question: str, facts: dict, grounded_on: list[str], provider: AIProvider | None) -> AssistantAnswer:
    """`facts` must already be real, retrieved data (see build_*_context
    below) -- this function never fetches anything itself, so it stays
    trivially unit-testable and impossible to accidentally ground on stale
    or unrelated data."""
    if provider is not None and facts:
        facts_json = json.dumps(facts, default=str)[:MAX_CONTEXT_CHARS]
        prompt = _SYSTEM_PROMPT.format(facts=facts_json, question=question)
        result = provider.complete(prompt, max_tokens=350)
        if result.ok and result.text and result.text.strip():
            return AssistantAnswer(
                answer=result.text.strip(),
                method="ai",
                ai_disclaimer="Generated by AI, grounded only in GrantSetu's real retrieved data -- verify against the original source before relying on it.",
                grounded_on=grounded_on,
                data_available=True,
            )
        # AI configured but failed/empty -- fall through to the rule-based
        # direct-facts answer rather than failing the request.

    return _rule_based_answer(facts, grounded_on)


# ---------------------------------------------------------------------------
# Context builders -- each returns a small, real fact dict for one "thing"
# the user might be asking about. None of these call an AI provider; they
# only read from the database/already-computed inputs.
# ---------------------------------------------------------------------------

def build_opportunity_context_from_imported(grant, source, changes) -> dict:
    return {
        "opportunity_title": grant.title,
        "funder": grant.funder,
        "source_name": source.name if source else None,
        "country": grant.country,
        "category": grant.category,
        "status": grant.status,
        "deadline": grant.deadline.date().isoformat() if grant.deadline else None,
        "description": grant.description,
        "eligibility_text": grant.eligibility_text,
        "application_url": grant.url,
        "extraction_method": grant.extraction_method,
        "last_verified_at": grant.last_verified_at.isoformat() if grant.last_verified_at else None,
        "recent_changes": [
            f"{c.change_type} (was: {c.old_value}, now: {c.new_value})" for c in changes
        ],
    }


def build_opportunity_context_from_historical(row) -> dict:
    import pandas as pd

    return {
        "opportunity_title": row.get("opportunity_title"),
        "funder": row.get("agency_name") if pd.notna(row.get("agency_name")) else None,
        "category": row.get("opportunity_category") if pd.notna(row.get("opportunity_category")) else None,
        "eligible_applicants": row.get("eligible_applicants_type") if pd.notna(row.get("eligible_applicants_type")) else None,
        "deadline": row["close_date"].date().isoformat() if pd.notna(row.get("close_date")) else None,
        "is_expired": bool(row.get("is_expired", False)),
        "award_ceiling": float(row["award_ceiling"]) if pd.notna(row.get("award_ceiling")) else None,
        "application_url": row.get("additional_information_url") if pd.notna(row.get("additional_information_url")) else None,
        "note": "This is a HISTORICAL U.S. federal opportunity record, not a live/current opportunity.",
    }


def build_ngo_context(profile, recommended_titles: list[str]) -> dict:
    return {
        "ngo_name": profile.name,
        "registration_type": profile.registration_type,
        "focus_areas": profile.focus_areas,
        "locations": profile.locations,
        "beneficiaries": profile.beneficiaries,
        "top_recommended_opportunities": recommended_titles[:5],
    }


def build_search_context(query: str, results: list[dict]) -> dict:
    """`results` are already-real AISearchResultItem dicts from a prior
    /opportunities/ai-search call, passed by the frontend so this endpoint
    never has to re-run the search (and can't drift from what the user is
    actually looking at)."""
    return {
        "original_query": query,
        "result_count": len(results),
        "results": [
            {
                "title": r.get("title"),
                "funder": r.get("funder"),
                "deadline": r.get("deadline"),
                "match_tier": r.get("match_tier"),
                "status": r.get("status_label"),
            }
            for r in results[:10]
        ],
    }


def build_analytics_context(analytics: dict) -> dict:
    """`analytics` is an already-computed payload from one of the
    /analytics/* endpoints (overview/trends/funders/categories/etc),
    forwarded by the frontend -- the backend calculates, this just lets AI
    explain what was calculated (see interview.txt: "Data science
    calculates. AI explains."). Never recomputed here."""
    return {"analytics": analytics}
